Use `ndarray.data` memory view in a call to sha1
On Python 3.6 `bytes(numpy.array([2]))` raises a

    TypeError: only integer scalar arrays can be converted to a scalar index